import { type Person } from "@/features/people/schemas/person-schema";

export const People: Person[] = [
  {
    id: 1,
    nationalNo: "N1",
    firstName: "Ahmed",
    secondName: "Khaled",
    thirdName: "Hozayfa",
    lastName: "Omer",
    gender: "Male",
    dateOfBirth: new Date("2000-01-15"),
    nationality: "Turkey",
    phoneNumber: "0533321",
    email: "ahmed.omer@gmail.com",
  },
  {
    id: 2,
    nationalNo: "N2",
    firstName: "Youssef",
    secondName: "Mahmoud",
    thirdName: "Ali",
    lastName: "Hassan",
    gender: "Male",
    dateOfBirth: new Date("1998-05-23"),
    nationality: "Egypt",
    phoneNumber: "0533322",
    email: "youssef.hassan@gmail.com",
  },
  {
    id: 3,
    nationalNo: "N3",
    firstName: "Fatima",
    secondName: "Mustafa",
    thirdName: "Saleh",
    lastName: "Demir",
    gender: "Female",
    dateOfBirth: new Date("1995-11-08"),
    nationality: "Turkey",
    phoneNumber: "0533323",
    email: "fatima.demir@gmail.com",
  },
  {
    id: 4,
    nationalNo: "N4",
    firstName: "Mohammed",
    secondName: "Ibrahim",
    thirdName: "Yasin",
    lastName: "Abdullah",
    gender: "Male",
    dateOfBirth: new Date("2001-03-17"),
    nationality: "Jordan",
    phoneNumber: "0533324",
    email: "mohammed.abdullah@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
  {
    id: 5,
    nationalNo: "N5",
    firstName: "Sara",
    secondName: "Omar",
    thirdName: "Nabil",
    lastName: "Kaya",
    gender: "Female",
    dateOfBirth: new Date("1999-09-30"),
    nationality: "Turkey",
    phoneNumber: "0533325",
    email: "sara.kaya@gmail.com",
  },
];
