#pragma once

#include <ctime>
#include <stdexcept>

#include "domain/value_objects/AccountId.hpp"
#include "domain/value_objects/ClientId.hpp"

enum class AccountStatus { ACTIVE, FROZEN, CLOSED };

class Account {
    public:

        // AccountId is generated by the use case and passed in.
        static Account openFor(AccountId id, const ClientId& clientId);

        static Account reconstitute(AccountId     id,
                                    ClientId      clientId,
                                    AccountStatus status,
                                    std::time_t   createdAt);

        // Throws std::logic_error if CLOSED or already FROZEN.
        void freeze();

        // Throws std::logic_error if CLOSED or already ACTIVE.
        void unfreeze();

        // Throws std::logic_error if already CLOSED.
        void close();

        const AccountId& id() const;
        const ClientId&  clientId() const;
        AccountStatus    status() const;
        std::time_t      createdAt() const;

        bool isActive() const;
        bool isFrozen() const;
        bool isClosed() const;

    private:

        Account(AccountId id, ClientId clientId, AccountStatus status, std::time_t createdAt);

        AccountId     _id;
        ClientId      _clientId;
        AccountStatus _status;
        std::time_t   _createdAt;
};